CREATE TABLE [model].[CleanModelInput]
(
	[ID]			  	 INT			      NOT NULL IDENTITY(1,1) ,
	[NotificationCode]   VARCHAR(255)		  NOT NULL,
	[ItemNumber]	  	 INT				  NOT NULL,
	[LayoutTaskId]	     INT				  NOT NULL,
	[TaskNumber]	     INT				  NOT NULL,
	[MaterialCode]	  	 VARCHAR(255)		  NOT NULL,
	[CreatedDate]	  	 DATETIME2(7)		  NOT NULL,
	[CompletedDate]	  	 DATETIME2(7)		  NULL,
	[TaskText]		  	 VARCHAR(MAX)		  NULL,
	[TaskCodeId]	  	 INT				  NOT NULL,
	[TaskCode]		  	 VARCHAR(255)		  NOT NULL,
	[TaskCodeText]	  	 VARCHAR(MAX)		  NULL,
	[SupplierVendorId]   INT				  NOT NULL,
	[SupplierVendorCode] VARCHAR(255)		  NOT NULL,
	[TaskOwnerId]		 INT				  NOT NULL,
	[TaskOwnerCode]		 VARCHAR(255)		  NOT NULL,
	[PlannedStart]		 DATETIME2(7)		  NULL,
	[PlannedFinish]		 DATETIME2(7)		  NULL,
	[TaskStatusId]		 INT				  NOT NULL,
	[TaskStatusCode]	 VARCHAR(255)		  NOT NULL,
	[DamageCodeId]		 INT				  NOT NULL,
	[DamageCode]		 VARCHAR(255)		  NOT NULL,
	[CauseCodeId]		 INT				  NOT NULL,
	[CauseCode]			 VARCHAR(255)		  NOT NULL,
	[GroupCodeId]		 INT				  NOT NULL,
	[GroupCode]			 VARCHAR(255)		  NOT NULL,
	[CategoryId]		 INT				  NOT NULL,
	[Category]			 VARCHAR(255)		  NOT NULL,
	[CodingCodeId]		 INT				  NOT NULL,
	[EngineProgram]		 VARCHAR(255)		  NOT NULL,
	[GeneralCode]		 VARCHAR(255)		  NULL DEFAULT (''),
	[IsTaskCompleted]	 INT				  NOT NULL,
	[IsItemCompleted]	 INT				  NOT NULL,
	[IsTurnback]		 INT				  NOT NULL,
	[IsLife]			 INT				  NOT NULL,
	[IsPlanning]		 INT				  NOT NULL,
	[Available]			 INT				  NOT NULL,
	[RunDate]			 DATETIME2(7)		  NOT NULL,

	CONSTRAINT PK_CleanModelInput PRIMARY KEY(ID)
)
